# Generated by Django 3.2.8 on 2021-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20211105_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
