# Generated by Django 3.2.8 on 2021-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
